name: root
channels:
  - conda-forge
  - defaults
dependencies:
  - aiofiles
  - fastapi
  - flask
  - gunicorn
  - pandas
  - python=3.6
  - rdkit
  - scikit-learn
  - scipy
  - nomkl
  - numpy
  - uvicorn
  - wtforms
  - pytest
  - requests
